export const cuisineList = [
  "Combo Meal", // 👈 Added this option
  "Rotli-Shaak-Dal-Bhat",
  "Bajri Rotla & Shaak",
  "Thepla & Pickle",
  "Dal Dhokli",
  "Kadhi-Khichdi",
  "Handvo",
  "Dhokla",
  "Fafda-Jalebi (Sunday Special)",
  "Sev Tameta Nu Shaak",
  "Ringan Bateta Nu Shaak",
  "Lasan Bateta",
  "Methi Thepla",
  "Patra",
  "Khichu",
  "Khichdi-Kadhi",
  "Bhakhri & Chunda",
  "Puran Poli",
  "Dal Fry & Jeera Rice",
  "Vagharelo Rotlo",
  "Gathiya & Chai (Breakfast)",
  "Dudhi Muthiya",
  "Surti Locho",
  "Misal Pav",
  "Sheero",
];

export const comboMeals = [
  "Gujarati Thali",
  "Rotli-Shaak-Dal-Bhat",
  "Kadhi-Khichdi",
  "Thepla & Pickle",
  "Dal Dhokli",
  "Handvo & Chutney",
  "Puran Poli & Aloo Sabzi",
  "Rajma-Chawal",
  "Paneer Butter Masala & Naan",
  "Chole Bhature",
  "Pav Bhaji",
  "Masala Dosa & Coconut Chutney",
  "Idli-Sambhar",
  "Veg Biryani & Raita",
  "Litti Chokha",
];
